name: Update And Publish Chocolatey Package
on: push

jobs:
  check-update:
    name: Check update
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install au
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install au
      - name: Check for new update
        shell: pwsh
        run: |
          cd .\flow-launcher\
          .\update.ps1
      - name: Commit update
        shell: pwsh
        run: |
          git diff
          git status
         
