name: Update And Publish Chocolatey Package

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  check-update:
    name: Check update
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.UPDATER }}
      - name: Install au
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install au
      - name: Check for new update
        shell: pwsh
        run: |
          cd .\flow-launcher\
          .\update.ps1
      - name: Publish & commit new update
        shell: pwsh
        run: |
          git diff --exit-code
          if ($LastExitCode -eq 1)
          {
            echo "`nNew update exists"
            # echo "`nPublishing new update to Chocolatey"
            # $package = Get-ChildItem -Path .\ -Filter *.nupkg -File -Name
            # choco push $package --api-key --source https://push.chocolatey.org/
            
            echo "`nCommiting to Git"
            git config --global user.email "choco_package_updater@flowlauncher.com"
            git config --global user.name "choco_package_updater"
            git add flow-launcher\flow-launcher.nuspec
            git add flow-launcher\tools\chocolateyinstall.ps1
            git commit -m 'new chocolatey package update'
            git push
          }elseif ($LastExitCode -eq 0)
          {
            echo "`nNo new updates"
          }
         
