name: Update And Publish Chocolatey Package
on: push

jobs:
  check-update:
    name: Check update
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Choco install
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install au
      - name: Install AU
        shell: pwsh
        run: |
          $host.Version -ge '5.0'
          #Install-Module au -Force
      - name: Check for new update
        shell: pwsh
        run: |
          cd .\flow-launcher\
          .\update.ps1
